# Generated by Django 5.1.3 on 2024-11-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('All', 'All'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed')], default='All', max_length=20),
        ),
    ]
